CONTRIBUTING.md

- we have to run both `db:push` and `db:seed`, and not the `seed` task that doesn't exists
- we have to use `pnpm dev` and not `turbo dev` because of the `--concurrency` option inside the root `package.json`

fix: contributing commands

---

apps/admin/package.json
apps/web/src/components/user/profile.tsx
apps/web/src/components/wizard/TestCasesEditor.tsx
packages/monaco/package.json
packages/monaco/src/code-editor.tsx
packages/monaco/src/index.tsx
packages/monaco/src/split-editor.tsx
packages/monaco/src/twoslash.ts
packages/monaco/src/vim-mode.tsx

Closes #397 
Changes:
- Fixed vim to work with the split editor
- Removed some of the code that wasn't being used anymore
- Added vim mode to the challenge creation pane
Further changes:
- Map `K` to hover in vim mode
- maybe reuse the code panel for the challenge creation?

Fixed vim mode in the editor

---

.prettierignore
README.md

- Run `format:fix` to format the README that had errors (https://github.com/bautistaaa/typehero/actions/runs/5979181595/job/16222741772#step:4:84)
- Ignore `.next` to not be formatted by Prettier

ci: fix formatting

---

apps/web/src/components/landing/feature-card.tsx

For #433
This removes the blurred background gradient on the absolutely positioned difficultly `div` for the right text. Then, it adds a background gradient from right to left with an opacity of the difficulty's background color on the outer `div`. I checked this works in light/dark mode on safari. Would be glad to make any needed changes!
Light mode:
Dark mode:

Solve - Selecting challenge in the learning tracks card (Landing Page) causes gradient to solidify

---

apps/web/src/components/landing/feature-card.tsx

This PR corrects a typo and will update the background of the difficulty item in the feature card to be `pink-300` and not `pink-30`.

Correct pink-30 to pink-300

---

apps/web/src/components/landing/waitlist/waitlist-form.tsx

This PR solves https://github.com/bautistaaa/typehero/issues/441 by keeping text white across light/dark mode on waitlist-form alert success.
Updated light-mode version (note: dark mode stays the same as before):

Fix: light mode waitlist banner

---

.github/workflows/contributors.yml

Run the `dl-git` script every 24 hours and create/update a PR to automatically update the contributors list.
To test on a PR we'll need a personal access token (see https://github.com/marketplace/actions/create-pull-request#action-inputs):

ci: add automatic contributors list update

---

packages/monaco/src/vim-keybindings.ts
packages/monaco/src/vim-mode.tsx

Added more vim keybinds related to #399 
Go to references is a bit odd because it opens a preview window that makes you put your hand back on the mouse :sweat_smile:

feat: add more vim keybindings to editor

---

apps/web/src/components/landing/community/community.tsx

We were using a `div` with a `backgroundImage`, which causes big payloads and unnecessary network requests when not in the viewport:

feat: use `next/image` for contributors avatars

---

packages/ui/src/components/dialog.tsx

This PR addresses https://github.com/bautistaaa/typehero/issues/479
Fixed position of close icon

[479] Bugfix :: Dialog box :: Aligned close icon with title

---

apps/web/src/components/ui/navigation.tsx

Another very small PR to highlight the current URL in the nav:
Home:
Explore:
Tracks:

feat(web): highlight current path (explore, tracks)

---

apps/admin/src/components/navigation.tsx
apps/web/src/app/_components/hero.tsx
apps/web/src/components/ui/footsies.tsx
apps/web/src/components/ui/navigation.tsx

This adds slightly higher contrast to the footer, landing description, and aria labels to our buttons in the navigation 👍🏻
(Note: performance is low only due to me being on dev server on local)

Fix: improve accessibility on landing (color/aria-labels)

---

apps/admin/src/app/_components/admin.actions.tsx
apps/admin/src/app/report/[id]/_components/report/challenge.report.tsx
apps/admin/src/app/report/[id]/_components/report/report.action.ts
apps/admin/src/app/report/[id]/report.action.ts
apps/web/src/app/challenge/[id]/getChallengeRouteData.ts
apps/web/src/app/challenge/[id]/solutions/[solutionId]/page.tsx
apps/web/src/app/challenge/[id]/solutions/page.tsx
apps/web/src/app/challenge/_components/comments/getCommentRouteData.ts
apps/web/src/app/explore/_components/explore.action.ts
apps/web/src/app/tracks/_components/track.action.ts
apps/web/src/components/user/dashboard/index.tsx
apps/web/src/components/user/dashboard/user-header.tsx
apps/web/src/components/user/profile.tsx

closes #454
- refactored "user" related queries to only include information that is displayed on front-end.
- replaced the queries to use `select` instead of `include` at some places.

chore: refactor user queries to prevent user info leak

---

apps/web/sentry.client.config.ts

closes (hopefully) #579
docs: https://docs.sentry.io/platforms/javascript/configuration/options/#environment

only allow sentry in staging/production envs

---

apps/web/src/components/wizard/TestCasesEditor.tsx
apps/web/src/components/wizard/index.tsx
packages/monaco/src/index.tsx

fix: Remove TS Diagnostics from validations

---

packages/monaco/src/editor-types.ts

This fixes a small issue with the `Extends` helper to make sure that if it is a union it still works

fix editor-types.ts

---

apps/web/sentry.client.config.ts

Following https://github.com/typehero/typehero/pull/616, we don't need Sentry replays at all
| Before | After |
|--------|--------|
| ![image](https://github.com/typehero/typehero/assets/43268759/584f2392-367e-4ce5-86f5-bd55f5f44d29) | ![Screenshot 2023-09-06 at 08 54 50](https://github.com/typehero/typehero/assets/43268759/e52fbdb6-ab40-4ef9-950d-6eb4f2ebbadb) |

feat(web): remove sentry replay

---

apps/web/src/app/[locale]/layout.tsx

Enable static site generation since all routes are now dynamic because of i18n.
| Before | After |
|--------|--------|
| ![Screenshot 2023-09-06 at 08 54 50](https://github.com/typehero/typehero/assets/43268759/21c00538-edf1-4c2b-b684-74a8ee089926) | <img width="818" alt="Screenshot 2023-09-06 at 12 23 12" src="https://github.com/typehero/typehero/assets/43268759/9fe5a46c-a6d1-421b-8a5d-82dd8a05bb9c"> |

fix(web): static site generation

---

apps/web/src/app/[locale]/challenge/_components/comments/comment.tsx
apps/web/src/app/[locale]/challenge/_components/comments/index.tsx

million js was breaking comment inputs for whatever reason. adding million ignore to the inputs parent component fixed the issue
#612 
tried to type multiple characters into input

(fix): millionjs breaks inputs

---

apps/web/src/components/ui/navigation.tsx

This removes @prisma/client from the client bundle
Due to the fact that we imported a value from prisma client instead of only types, the whole prisma/client was bundled into the client bundles. This will remove roughly 26kb gzipped. 
I was not sure how to handle this best and also tried to create a server action for this. But in the end I think this works too as
1. The types are pretty stable and don't change
2. if the schema changes linting also will fail making sure the object will be adjusted
We have too much JS for a static page
pnpm build -> check imported chunks for prisma output

remove prisma from client bundle

---

apps/web/src/app/[locale]/challenge/_components/reset-editor-button.tsx

Added tooltip for reset button in the challenge editor 
Closes #622 
Maintain consistency and provide the user info with what the button does
By hovering over the reset button
https://github.com/typehero/typehero/assets/32938743/b873dade-a3bc-48cc-a831-4b319835fa9c
@PickleNik please have a look!

tooltip for reset button

---

apps/web/package.json
apps/web/src/app/[locale]/page.tsx
apps/web/src/app/[locale]/waitlist/page.tsx
pnpm-lock.yaml

Enable static rendering only for `/`, so it doesn't break other pages that have server actions.

feat(web): static rendering on `/`

---

apps/admin/src/components/navigation.tsx
apps/web/src/components/ui/navigation.tsx

Changes z-10 to z-0 on the nav components -- this ensures tooltips are rendering over them (tooltips already have z-50, but am not sure why it is rendering below the nav)
Should fix #638
Necessary to ensure that tooltips are readable always (future proofs the pages as well, pending any changes/additions to icon buttons on nav)
Tested visually on challenge/submissions page

fix: Ensures tooltips in challenges render under nav

---

packages/monaco/src/index.tsx
packages/monaco/src/split-editor.tsx

In light mode, the test panel dragger maintained the same color as the dark mode.
Tested visually in all the browsers.
Before
https://github.com/typehero/typehero/assets/32938743/0ee3fdaa-60b3-46c1-98cf-8ce960cd4870
After
https://github.com/typehero/typehero/assets/32938743/8945bfeb-ec72-476a-8561-31c289fcb0ea

Fixed light mode issue with test panel

---

apps/web/src/app/[locale]/challenge/_components/description/index.tsx
apps/web/src/app/[locale]/challenge/_components/vote.tsx
packages/ui/src/components/button.tsx

This PR solves #654. I added the utility CSS class `disabled:cursor-not-allowed` instead of `disabled:pointer-events-none` so the tooltip can show on the `Button` component.
Issue #654 
Works on light and dark mode. Only shows up if not logged in.

Fix: 654 bug submit button disabled when not logged in

---

apps/web/src/app/[locale]/challenge/_components/comments/comment-input.tsx

disable comment input box while user was logged out
this PR fixes #649
updated placeholder of comment input if user isn't logged in

disable comment input box while user was logged out #649

---

packages/monaco/src/index.tsx
packages/monaco/src/split-editor.tsx

Adds tooltips and aligns functionality of resize handle
This PR enables tooltips for the show / hide tests button as well as for the test status icon.
Additionally it adds tie functionality to close the test panel by double clicking on the resize handle. Just like how it works for the leftwrapper
Visually by looking and clicking
https://jmp.sh/Nd9CBkjY

Adjust tests panel

---

packages/monaco/src/editor-hooks.ts
packages/monaco/src/split-editor.tsx
packages/monaco/src/utils.ts

I moved the `deps` from `useResetEditor` to `subscribe` since they are only used to make sure the callback in that function isn't stale. 
Tested locally by clicking the reset button a bunch of times.

chore: refactor type checking

---

apps/web/src/components/carousel.tsx

This just adds a unique ID to our carousel component left/right buttons. This solves the issue where we are selecting on non-unique IDs in the DOM 👍🏻
https://github.com/typehero/typehero/issues/242
Nice Lighthouse score
Lighthouse report
Before:
After:
No issues noted in the lighthouse report (ayo???!)

Bugfix: add unique ids to Carousel left/right buttons

---

apps/web/src/app/[locale]/tracks/_components/track-enrolled-section.tsx

This PR fixes the issue where the skeleton card was not adapting to the lightmode
Closes #742 
Tested visually
Before
https://github.com/typehero/typehero/assets/32938743/a046c8c8-5687-49ac-b8cd-6cc22810f517
After
https://github.com/typehero/typehero/assets/32938743/bb8e4038-ce57-4565-8088-17242b1e8cbf

Fixed light mode issue with a "No tracks yet " skeleton

---

apps/web/src/app/[locale]/challenge/_components/comments/comment.tsx
apps/web/src/app/[locale]/challenge/_components/comments/index.tsx
apps/web/src/app/[locale]/tracks/_components/track-challenge-card.tsx

This PR includes the following changes:
* Update pagination of replies to use a cursor in the `useInfiniteQuery` for replies.
* This enables increasing the size of the first "page" of replies (replies above the "Load More") to include the deep-linked reply.
* Adjust `scrollIntoView()` to use the `"nearest"` edge option ([reference](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView#block)).
* This prevents a bug where the comment container is shifted "up" when the DOM attempts to scroll the preselected reply into view on first paint. (We can iterate here I'm not in love with it, but as-is this fixes the bug on `main`)
* Adjusted background color of selected page button ([1], [2], [3]) so that it color matches the selected tab in the head of the sidebar ("Description", …

Support deep link to paginated replies

---

apps/web/src/app/[locale]/settings/_components/profile.tsx

The Bio editor was not responsive and was messing up on the mobile

style: fix bio editor responsiveness

---

packages/email/package.json

https://react.email/docs/cli
`--skip-install ` added this to react-mail script
Closes #
#779 
yarn.lock file was not installed and `pnpm run dev` started server without issue

fix: react-email script --skip-install

---

apps/web/src/components/rich-markdown-editor.tsx

`system` or `undefined` values of theme were not being handled appropriately. Added a switch case to map possible theme values to `data-color-mode` values.
As per [next-theme docs](https://www.npmjs.com/package/next-themes#API) the `defaultTheme` attribute is set to the value `system`. While setting `data-color-mode` in RichMarkdownEditor, this causes it to default to `light` theme for the very first time (when `theme` in localStorage is set to `system`). After switching themes manually, the `theme` value in localStorage resets to either `dark` or `light` causing no further problems.
I resolved it by creating a switch block for setting `data-color-mode` based on `theme` and handling the default case. 
Alternate method: Enforcing a application wide default theme by setting `defaultTheme` …

fix: Dark mode profile bio wrong theme colors

---

apps/web/src/app/[locale]/(playgrounds)/challenge-playground/challenge-playground-store.ts
apps/web/src/app/[locale]/(playgrounds)/challenge-playground/description.tsx
apps/web/src/app/[locale]/(playgrounds)/challenge-playground/layout.tsx
apps/web/src/app/[locale]/(playgrounds)/challenge-playground/left-wrapper.tsx
apps/web/src/app/[locale]/(playgrounds)/challenge-playground/page.tsx
apps/web/src/app/[locale]/(playgrounds)/challenge-playground/wrapper.tsx
apps/web/src/components/navigation.tsx
apps/web/src/middleware.ts
packages/monaco/src/index.tsx
packages/monaco/src/split-editor.tsx

create an editable view of the challenge layout for internal users only so we can dogfood our challenges during creation
this works-ish now. will fix saving tests to local storage next
challenge creators need a way to test their challenges as a user would.
locally
https://github.com/typehero/typehero/assets/3660667/e7c0eb5d-75e5-4529-ad54-cd9c137d55e5

feat: adds a challenge playground

---

apps/web/src/app/[locale]/challenge/_components/comments/comment.tsx

use lucide `<Flag />` icon for report comment button
N/A
|Before|After|
|---|---|
|![image](https://github.com/typehero/typehero/assets/7817695/4894279a-3c4c-4d68-81fe-234e07ea519b)|![image](https://github.com/typehero/typehero/assets/7817695/3a1642f7-a63c-4792-98f5-53c959b0583a)|

fix: use flag for report comment icon

---

.github/workflows/quality.yml
LOCAL.md
apps/web/tests/e2e/auth.setup.ts
apps/web/tests/e2e/unauthenticated/challenge.test.ts

- Made tests rerunnable by adding `connectOrCreate` and deleting records
- Added docs to run tests locally
- Fix e2e workflow
Closes #764

feat: make tests idempotent and add docs

---

apps/web/src/app/[locale]/challenge/_components/comments/comment.tsx
packages/ui/src/components/badge.tsx
packages/ui/src/components/button.tsx

Changelog
* feat: `dark` background+hover for `"secondary"` and `"outline"` button variants
* feat: `dark` backround for `"secondary"` badge variant
* fix: tooltips on comment "Report" and "Delete" action buttons
N/A
locally in Chrome & Brave, be sure you're in system dark mode
|New|
|---|
|![image](https://github.com/typehero/typehero/assets/7817695/237e3d0a-8d2c-4f42-b137-a0144a44ec92)|
|![image](https://github.com/typehero/typehero/assets/7817695/e6ed3105-d7b4-459b-823f-77435dc28095)|
|![image](https://github.com/typehero/typehero/assets/7817695/d252ee6d-6e0c-44fa-aa4e-a8d77086fb7e)|
|![image](https://github.com/typehero/typehero/assets/7817695/0693195c-1a96-47c5-9a0f-8076bf58def0)|
https://github.com/typehero/typehero/assets/7817695/8088afe3-0cb4-4618-92c1-bcb9879baea9

feat: add dark style to `secondary` variants

---

apps/web/src/app/providers.tsx

Move react-query logo to top-right corner
Closes #794
Logo does not interfere with anything in top-right corner
Tested locally

[Feat] :Move react-query logo to top right corner

---

apps/og-image/app/api/challenge/route.tsx
apps/og-image/utils/zodParams.ts
apps/web/src/app/[locale]/challenge/[id]/page.tsx

Closes #819
Markdown isn't easily rendered in the OG image. I was originally going to take the first sentence of a challenge but this posed a few issues (eg. what if someone doesn't write in full sentences? what if markdown is in the first sentence? etc).

fix: make challenge OG description renderable and deterministic

---

apps/web/src/app/[locale]/challenge/_components/comments/getCommentRouteData.ts
apps/web/tests/e2e/authenticated/comment.test.ts

visiting a deep link to a deleted comment renders the challenge page with the comment view open, but stuck in an "broken loading state"
i sus'd an error message in the server output:
```bash
web:dev: Invalid `prisma.comment.findMany()` invocation:
web:dev: 
web:dev: 
web:dev: Error in query graph construction: AssertionError("Invalid value for skip argument: Value can only be positive, found: -10")
web:dev:  X PrismaClientUnknownRequestError: 
web:dev: Invalid `prisma.comment.findMany()` invocation:
web:dev: 
web:dev: 
web:dev: Error in query graph construction: AssertionError("Invalid value for skip argument: Value can only be positive, found: -10")
web:dev:     at async getPaginatedComments (./src/app/[locale]/challenge/_components/comments/getCommentRouteData.ts:125:22)
```
ah-ha, …

fix: fix error on deep link to deleted comment

---

apps/web/src/app/[locale]/challenge/[id]/submissions/loading.tsx

It was inheriting the loading skeleton from DescriptionSkeleton as the submissions folder did not have any loading.tsx so it looked the nearest loading.tsx which was present in the root folder. Had to put the loading.tsx out of the catch all route cause it renders the DescriptionSkeleton for a split second .
Closes #829
https://github.com/typehero/typehero/assets/86520455/ba7adfe2-9bf9-4130-9dd1-78d210d93ba9

fix: inherit submission skeleton 

---

.github/ISSUE_TEMPLATE/new-challenge.yml
README.md
apps/web/src/app/[locale]/_components/feature-card.tsx
apps/web/src/app/[locale]/_components/hero.tsx
apps/web/src/app/[locale]/login/_components/LoginButton.tsx
packages/db/seed/data/tracks.ts

I realize this is a tiny thing but it's the very first thing my eyes read on the landing page so I thought worth a 10 second fix (especially considering the `GitHub` button right below it has it correct).
figured while we're here might as well catch some TypeScript typos as well: if any of these cause a problem we can just drop the commit

fix typo: GitHub

---

packages/ui/src/components/markdown.tsx

fix(markdown): remove fixed font-size from inline code

---

apps/web/src/middleware.ts

Prevent this error when navigating on the main page: ![Screenshot 2023-10-18 at 08 14 52](https://github.com/typehero/typehero/assets/43268759/f31e2e9c-8fad-48d0-9819-35521714e748)
It's caused by the toolbar when authenticating, but Next.js doesn't seem to handle it properly and it's instead executed by our pages, which extracts the locale to be `.well-known` instead of `en`:

fix(web): i18n error on main page

---

apps/web/src/app/[locale]/[username]/_components/dashboard/overview-tab.tsx

reproduce on my bio on staging https://staging.typehero.dev/@ayrock-dev
|Before|
|---|
|<img width="350" alt="image" src="https://github.com/typehero/typehero/assets/7817695/0fe9064c-a2bf-4931-a827-f145ee013c75">|
|After||
|---|---|
|<img width="350" alt="image" src="https://github.com/typehero/typehero/assets/7817695/18ccc98c-1bd0-4eae-8f93-ac7067e24cae">|<img width="150" alt="image" src="https://github.com/typehero/typehero/assets/7817695/3ad2b002-c267-47a1-ad67-15c0ae03e603">|

fix: profile bio width

---

apps/web/src/app/[locale]/challenge/_components/description/index.tsx
packages/monaco/src/settings-store.ts
packages/ui/src/components/markdown.tsx

Changed the default font size of prompts to 13px and made the font size in the code block inherited
Closes #944 
#944 
No

feat: Inherited font sizes for challenge prompts

---

apps/web/src/app/[locale]/not-found.tsx
apps/web/src/utils/server/get-random-challenge.ts

I've made some improvements to the 404 page. The changes cater to both logged-in and logged-out scenarios, providing clear options for users to navigate effectively. 
For logged-in users encountering a 404 page, two buttons are displayed
- Go to tracks: redirects the user to the tracks page
- I'm feeling lucky: redirects the user to a random challenge page which is fetched from the `Challenge` table
For logged-out users encountering a 404 page, one button is displayed
- Go to home: which redirects to the '/' home page
Closes #940 
By navigating to an invalid URL
States when the user is not logged in and goes to an invalid URL
States when the user is logged in and navigates to an invalid URL
https://github.com/typehero/typehero/assets/32938743/8c6b521a-27a7-4692-aa0a-51643f6e0350

Feature: 404 page

---

apps/web/src/app/[locale]/[username]/_components/dashboard/index.tsx
apps/web/src/app/[locale]/settings/_components/edit-profile-tab.tsx
apps/web/src/app/[locale]/settings/_components/settings.tsx

- Removes the links from the settings page because they're un-needed
- Add null check for user links length
- Equal alignment of profile items on left side
Working on this with Trash when deploying to prod and we saw some visual issues
Visually w/ CSS and Browser
Settings (without links and equal gap with profile)
Profile (re-alignment with equal gap now):

Update Settings/Profile with Small Changes

---

challenges/generic-function-arguments/metadata.json
challenges/generic-function-arguments/tests.ts

I was trying to avoid getting into literal types, but at this point it's easier and (probably appropriate) to just assume that knowledge by the time of this challenge.
Fixed the tests for `generic-function-arguments`'s `identity` type.
Closes https://github.com/typehero/typehero/issues/974
manually including the solution.

fix(challenge) generic-function-arguments tests

---

packages/db/mocks/challenges.mock.ts

The titles from the https://github.com/type-challenges/type-challenges repo can have "." in the title, causing our slugs to be malformed for valid URLs.
Solved by adding extra regex to our `slugify` function.
Closes #971 
To fix our challenge URLs
In the browser checking (see screenshot)

Fix malformed slugs from type-challenges repo

---

challenges/type-aliases/prompt.md

Improves the prompt of the type-alias challenge to signal to users that they might be asked to create a type alias.
It may be confusing to see some type aliases pre-created and have some missing.  Indeed, in this specific challenge this is very much intended behavior because we want users to get some on-the-ground experience with writing type-aliases from scratch.
Closes # https://github.com/typehero/typehero/issues/1031
thanks again @is-it-ayush for bringing this up

[Feature] challenge(`type-alias`) improves the prompt

---

packages/db/seed/prod.ts
packages/ui/package.json
packages/ui/src/components/markdown.tsx
pnpm-lock.yaml

Fix the tags being escaped in the markdown.
Closes #1033 
This fixes the `details` and `summary` tags being escaped and shown as strings instead of an actual html element.

fix: `react-markdown` escaping `details` and `summary` tag

---

apps/web/src/styles/globals.css
apps/web/tailwind.config.ts
packages/ui/src/components/form.tsx
packages/ui/src/components/markdown.tsx

This gives the **form message** in `form.tsx` more color contrast. Particularly, the form message when choosing a title for a solution meets a `4.5:1` color contrast ratio in dark mode. It does not meet this ratio for the message when leaving a comment in dark mode. Light mode has it's own issues... Anyone have any thoughts?
Closes #1029

Form Message Color Contrast

---

apps/web/src/app/[locale]/challenge/_components/comments/comment.action.ts
apps/web/src/app/[locale]/challenge/_components/comments/delete/index.tsx

Ensure User is the author of a comment before deleting
Closes #1043 
Malicious Users can currently delete other users comments
Manually
Simply change the Comment ID in the request payload to any comment ID

Ensure User is the author of a comment before deleting

---

packages/monaco/src/split-editor.tsx

- Add a save handler that listens for Ctrl + S key combination and displays a toast notification with the title "Saved" and the description "Your code has been saved" when the current wrapper ref has focus
Pressing 'Ctrl+S' in the code editor triggers the browser's default save function. This behavior is counterintuitive for users accustomed to IDEs where 'Ctrl+S' typically saves progress within the app or performs another action, such as running tests. Disabling this or binding 'Ctrl+S' to a more useful function, like running tests, would enhance usability.
Closes [#1050](https://github.com/typehero/typehero/issues/1050)
This change would streamline the coding experience and align the editor's functionality with common developer practices, improving the platform's overall user …

feat: Simplify 'Ctrl+S' Functionality in Editor to Prevent Default Save Prompt

---

apps/og-image/app/api/challenge/route.tsx

Fixes dimensions of the challenge twitter-card
Adjust twitter-card OG image
Closes https://github.com/typehero/typehero/issues/1060
Needs to be deployed to branch in order to test in twitter

[Bug]: Challenge OG image does not render correctly on twitter

---

apps/web/package.json
apps/web/src/middleware.ts
pnpm-lock.yaml

`@vercel/toolbar` makes a call to `/.well-known/vercel-user-meta` which seems to bypass `generateStaticParams` so we get a `.well-known` dynamic locale segment, which doesn't exist.
Closes #1064
- `cd apps/web && vc link`
- `pnpm dev` then navigate to the homepage, there shouldn't be any error logged in the terminal
UPDATE:
Only bump next-international to include https://github.com/QuiiBz/next-international/pull/252

fix(web): i18n locales error due to toolbar

---

apps/web/src/app/[locale]/[username]/bookmarks/page.tsx
apps/web/src/app/[locale]/[username]/completed/page.tsx
apps/web/src/app/[locale]/[username]/in-progress/page.tsx

Users are able to view other user's completed tracks, bookmarks, and in progress challenges. This makes sure the user must be logged in and match the name
Closes #

fix: access to user profile sections

---

apps/web/src/app/[locale]/challenge/_components/comments/comment-input.tsx
apps/web/src/app/[locale]/challenge/_components/comments/comment.tsx
apps/web/src/app/[locale]/challenge/_components/comments/comments.constants.ts
apps/web/src/app/[locale]/challenge/_components/comments/comments.hooks.tsx
apps/web/src/app/[locale]/challenge/_components/comments/delete/index.tsx
apps/web/src/app/[locale]/challenge/_components/comments/getCommentRouteData.ts
apps/web/src/app/[locale]/challenge/_components/comments/index.tsx

- fixed https://github.com/typehero/typehero/issues/1095
- Moved comments/replies logic into it's separate hooks
- `CommentsInput` no longer have 2 input values states (external and internal)
- Deleting last comment on 2 (or other page different than 1), not automatically goes back to previous page
Closes https://github.com/typehero/typehero/issues/1095
This came-up as work trying to fix https://github.com/typehero/typehero/issues/1095. So I decided to refactor it a little bit.
Comments components are kinda mess right now, and full of prop drilling. As a next step I'd love to fix composition over there, so it would be easier to maintain and extend if needed in the future

[Feat] Refactor comments CRUD

---

apps/web/src/app/[locale]/page.tsx

Adds `getStaticParams` inside `generateStaticParams` to `[locale]/page.tsx` as per https://next-international.vercel.app/docs/app-static-rendering
Closes #

[Fix]: Make homepage static again

---

apps/web/src/app/[locale]/challenge/_components/challenge-track-navigation.tsx

made two small changes:
1) In previous index should return the track challenge also if its zero and not just greater than zero
2) named index to prevIndex and nextIndex for better readability  
`return index > 0 ? trackDetails!.trackChallenges[index] : null;`
this will return null also if the index is 0 but since indexing starts from 0 
so the code should look like
`return index >= 0 ? trackDetails!.trackChallenges[index] : null;`
https://github.com/typehero/typehero/issues/1106
Closes #

fix: navigate to second track and you cannot hit the previous button

---

apps/web/src/app/[locale]/(profile)/[username]/_components/dashboard/_actions.ts
apps/web/src/app/[locale]/(profile)/[username]/_components/dashboard/challenges-progress.tsx
apps/web/src/app/[locale]/(profile)/[username]/_components/dashboard/overview-tab.tsx

challenges count of logged in user is visible in every profile.
Previously the logged in user's solved problems count was visible on each profile. 
Now it comes to two fixes, either
1. Make everyone's progress public.
2. Make it private to logged in user's profile only.
Made it public for now. Will change based on the feedback.
Closes #

fix: challenges count of logged in user is visible in every profile.

---

apps/web/src/app/[locale]/_components/community/community.tsx
apps/web/src/app/[locale]/_components/features.tsx
apps/web/src/app/[locale]/_components/hero.tsx
apps/web/src/app/[locale]/explore/_components/explore-section.tsx
apps/web/src/components/rich-markdown-editor.tsx

This PR makes badge text unselectable and resolves the text highlighting issue in the rich markdown editor:
[https://github.com/typehero/typehero/issues/1097](https://github.com/typehero/typehero/issues/1097)
Closes #1097 
Tested on Firefox
See related issue and above.

fix: text selection is invisible

---

apps/web/src/app/[locale]/challenge/_components/comments/comment.tsx

Just added a whitespace
could have used padding but for that i would have to wrap the "Last edited at" string into a div, 
just to not increase any code length and to fix the issue in minimum i used a white space........
https://github.com/typehero/typehero/issues/1133
Closes #
before:
after:

fix: no space between last edited at and date in comments

---

apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/edit-solution.tsx

removed unnecessary z-index, it got fixed
Closes https://github.com/typehero/typehero/issues/1142
[Screencast from 17-11-23 11:25:30 PM IST.webm](https://github.com/typehero/typehero/assets/114667178/e503857d-63b8-462d-9f00-97f97d282191)

fix: z indexing problem when comments toggle while editing the solution

---

CONTRIBUTING.md
packages/monaco/src/index.tsx

Seems like log was added in https://github.com/typehero/typehero/commit/99681058b8562ab8975d357bfeeec21b1248ccd0

Fix typo in contributing readme + remove console log

---

challenges/index-signatures/tests.ts

`pnpm run lint:markdown` was failing due to spell because ThePrimeagen wasn't recognized as a word lol
also removed an extra extra word in the text of the other test

fix pnpm run lint:markdown failing

---

apps/web/tests/e2e/authenticated/comment.test.ts

This PR fixes the previously failing e2e test for comments by adding a timeout. I noticed that the deletion of the comment takes some time to get reflected in the frontend.
Closes #1180
Test runs without failure locally (hopefully also in the CI)

fix(e2e-test): add flaky test (`comment.test.ts`) by adding timeout

---

apps/web/src/app/[locale]/challenge/[slug]/submissions/[[...catchAll]]/_components/overview.tsx

The overview page `Solution` button text is not very readable in light mode.
Closes #

The text color of the solution button should remain white.

---

apps/web/src/app/[locale]/(profile)/[username]/_components/dashboard/_actions.ts
apps/web/src/app/[locale]/_components/hero.tsx
apps/web/src/app/[locale]/aot-2023/_components/index.tsx
apps/web/src/app/[locale]/challenge/_components/comments/index.tsx
apps/web/src/app/[locale]/explore/_components/explore-card.tsx
apps/web/src/app/[locale]/providers.tsx
apps/web/src/app/[locale]/tracks/_components/track-challenge-card.tsx
pnpm-lock.yaml
tooling/config-eslint/next.js
tooling/config-eslint/node.js
tooling/config-eslint/package.json

I added a rule to remove unused imports so this will apply when running `pnpm lint:fix`. I am doing this PR so it doesn't muddy up the `Files changed` section 👍🏻 
https://turbo.build/repo/docs/handbook/linting/eslint - From this documentation, we extend from our global eslint file. So, I made the change here so it will apply to all of our directories in the `apps/` dir that extend it.
Closes #1163 
Remove unused imports from our repo
Yes I added an unused import in a random file in `apps/web/` then ran `pnpm lint:fix` and it does properly remove it now.

Add Linter Fix Rule to Enable Unused Imports in Lint config

---

apps/web/src/app/[locale]/_components/countdown-timer.tsx
apps/web/src/app/[locale]/aot-2023/_components/index.tsx

Adds countdown until aot-2023 starts. It will disappear when reaches 0.
Desktop:
Mobile:

feat: add countdown to aot-2023

---

apps/web/src/app/[locale]/(profile)/[username]/_components/dashboard/_actions.ts

fix the aot bronze badge showing up in practically the opposite situation as intended
testing steps:
on preview checkout a profile like
https://typehero-git-fix-aot-bronze-badge-trash-company.vercel.app/@ayrock-dev
or
https://typehero-git-fix-aot-bronze-badge-trash-company.vercel.app/@bautistaaa
screenshot is as expected, can take a look on preview

fix: fix aot bronze badge

---

apps/web/src/app/[locale]/(profile)/[username]/_components/profile-skeleton.tsx
apps/web/src/app/[locale]/(profile)/[username]/bookmarks/loading.tsx
apps/web/src/app/[locale]/(profile)/[username]/completed/loading.tsx
apps/web/src/app/[locale]/(profile)/[username]/in-progress/loading.tsx
apps/web/src/app/[locale]/(profile)/[username]/loading.tsx
apps/web/src/app/[locale]/(profile)/[username]/shared-solutions/loading.tsx
apps/web/src/app/[locale]/settings/_components/settings-skeleton.tsx

Fixes loading skeleton not matching content of the page
Closes #
Triggering suspense boundary in react devtools
| Before  |After   | 
|--------|-------|
| <img width="232" alt="Screenshot 2023-11-30 at 19 02 31" src="https://github.com/typehero/typehero/assets/131662061/a7bde632-e793-46ff-a188-0ae0be96af01">  | <img width="231" alt="Screenshot 2023-11-30 at 19 04 29" src="https://github.com/typehero/typehero/assets/131662061/1ba8980c-4364-4eeb-88b7-cfdfd4cbccb7"> |
|  <img width="199" alt="Screenshot 2023-11-30 at 18 44 32" src="https://github.com/typehero/typehero/assets/131662061/9041ac44-b5dd-4068-b3e5-5c34b19b1d90"> |  <img width="243" alt="Screenshot 2023-11-30 at 18 50 34" src="https://github.com/typehero/typehero/assets/131662061/41ccc4ed-465b-4a95-b131-2961abee32c1"> |   
| <img …

[Fix] upade loading skeletons on profile pages to match page content

---

packages/monaco/src/index.tsx

Changes the text to say Login to Submit instead of just Submit when signed out during Advent of Typescript to improve UX
Closes #1216 
I didn't hover over the button for long enough for the popover to load and got confused
Ran locally

feat(aot): update submit button to say login to submit when signed out

---

packages/ui/src/components/markdown.tsx

style(markdown): add margin bottom to ul and ol tag in markdown

---

apps/web/src/app/[locale]/aot-2023/_components/card-grid.tsx
apps/web/src/app/[locale]/challenge/[slug]/getChallengeRouteData.ts
apps/web/src/app/[locale]/challenge/[slug]/page.tsx
apps/web/src/app/[locale]/challenge/[slug]/submissions/[[...catchAll]]/save-submission.action.ts
apps/web/src/app/[locale]/challenge/[slug]/wrapper.tsx
apps/web/src/utils/aot.ts

- challenge submission should not taking user id
- cant query aot challenges if before reveal
- cant submit answer to aot challenges if before reveal

fix challenges

---

apps/web/src/app/[locale]/providers.tsx

On theme change, some of the components have a visible blinking effect. 
**Examples:**  
This will effect all of the components that have either `transtion-property : color, background-color` or `transition-property: all`  and  a `transtion-duration`. 
This can be solved by setting the  `disableTransitionOnChange`  prop to `true` in `next-themes` provider.

disable transition on theme change

---

packages/db/seed/prod.ts

Fixes a typo in the URL of TypeHero's profile, it was `typhero.dev` and this fixes it to be `typehero.dev`. This is the only place that string appears in the codebase so I'm hoping this fixes it?
Closes #1246.

fix: TypeHero's profile URL

---

apps/admin/src/app/dashboard/tracks/[trackId]/_components/update-track-form.tsx
apps/admin/src/app/dashboard/tracks/_components/add-track-form.tsx
apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/edit-solution.tsx
apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/solution-editor.tsx
apps/web/src/app/[locale]/challenge/_components/settings/settings-form.tsx
apps/web/src/app/[locale]/claim/claim-form.tsx
apps/web/src/app/[locale]/settings/_components/edit-profile-tab.tsx
apps/web/src/app/[locale]/wizard/_components/NextBack.tsx
apps/web/src/app/[locale]/wizard/_components/index.tsx

Visual feedback on clicking buttons is important. Buttons that don't react to a click tend to confuse users and get double clicked. Poof poof one-two combo
Just using `form.formState.isSubmitting` to disable the submit button in all react-hook-form forms that I could find.
Clickety click on a submit button. Typescript seems to be happy.

fix: disable submit buttons when submitting

---

packages/monaco/src/split-editor.tsx

This PR fixes the handling of diagnostic message chains in the Monaco split editor. Instead of
assuming that `messageText` is a string, we now call out to TypeScript to flatten the message for
us, which fixes the occasional `[object Object]` error messages.
Closes #1272.
This PR ensures that error messages are displayed properly in Monaco in order to provide adequate
information about what's wrong to the user.
I've confirmed that the `readonly` error is no longer an issue.

fix(monaco): handle diagnostic message chains

---

apps/web/src/app/[locale]/explore/_components/explore-section.tsx

fix background blur color on light mode
Closes #
Before:
After:

bug: background blur color fix on light mode

---

apps/web/src/app/[locale]/(profile)/[username]/_components/dashboard/overview-tab.tsx

Bio extends out when typing in a really long character string. Hence, max width and break words is set to prevent this type of case from happening. If there's any disagreement with the max-width just let me know and I can change it! 
https://github.com/typehero/typehero/issues/1280 
See description
Tested locally on dev on both mobile view (Iphone 14) and browser with strings that have 256 characters and also tested with other long strings.

issue-1280 extend out issue on bio with really long character string. 

---

packages/ui/src/components/markdown.tsx

I add text-overflow: ellipsis to p in markdown so width of the a tag does not exceed the width of the p tag.
I add white-space:nowrap to a in markdown to prevent automatic line breaks in <a> tags at firefox browser
#1310

issue 1310 : The <a> tag inside the <p> tag extends wider than the width of the <p> tag. 

---

apps/web/src/app/[locale]/_components/community/community.tsx
apps/web/src/app/[locale]/_components/features.tsx
apps/web/src/app/[locale]/_components/newsletter-banner.tsx
apps/web/src/components/footsies.tsx

This PR fixes following a11y issues on the homepage
- Adds discernible name for github & twitter links in the footer using sr-only tailwind utility
- Fixes color contrast by changing text-black/50 to text-black/60 on light mode
Relates to #242
It fixes these issues (Multiple contrast issues in light mode on homepage)

Fix: Improve a11y on homepage (Added link names & fixed contrast)

---

apps/web/src/utils/server/get-similar-challenges.ts

notIn was exluding only the solved challenges, adding the challengeId ( challenge user is currently on ) to the array of challengeIds to exluded fixes the issue
earlier: only solved challengeId's were exluded
now: along with solved challengeId's , current challengeId is also being excluded
https://github.com/typehero/typehero/issues/1316
Closes #
Before:
[Screencast from 12-12-23 08:35:37 PM IST.webm](https://github.com/typehero/typehero/assets/114667178/2a880a20-79f6-466e-8884-d95e2972f772)
After:
[Screencast from 12-12-23 08:36:29 PM IST.webm](https://github.com/typehero/typehero/assets/114667178/549b2c0b-e1ac-45e5-a78f-5215fb5a55d7)

fix: same challenge being suggested again

---

apps/web/src/app/[locale]/explore/_components/view-more-button.tsx

Basically wraps whole `ViewMoreButton` in the Next `<Link/>` and removes onClick handler.
Since it doesn't use `useRouter` anymore - we can remove `"use client"` directive too
Closes #1329
It's a bit painful to manually duplicate a page when you want to go for specific difficulty section. Making a link _an actual_ link resolves the issue
Manually tested
before/after video:
[github hates .mkv - here is youtube link](https://www.youtube.com/watch?v=tFTeVAg71mo)

fix: make "view more" button on /explore an actual link instead of button with onClick

---

apps/web/src/components/search/search-provider.tsx

This PR fixes the infamous Instantsearch query on mount issue by detecting empty searches and
resolving with an empty response. Previously, every time someone loaded the landing page (or any
page that has the search box), a query was performed, which racked up a lot of requests. Not ideal,
considering there's a quota.
N/A
Basically the description.
I've confirmed locally that the newly added code correctly detects empty queries and handles them
locally as opposed to hitting Algolia.
N/A

fix(search): don't perform empty queries

---

apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/index.tsx
apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/solution-detail.tsx
apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/useGetQueryString.tsx
apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/useQueryParamState.ts

add page querystring to url when user navigating solution
Change to the browser's back action when pressing the back icon on the solution page.
Closes #1325 
After users view a solution on the Solutions page, they can return to the current page they were viewing.
When user press bottom navigation page param added to query string of url
When the filter is changed, the page changes to 1.
When the user sees the solution and go back user can return to the current page .
When user press the back icon on the solution page user can return to the current page they were viewing.
https://github.com/typehero/typehero/assets/62943813/4a9759ec-4677-419d-a6c3-62718f2d6887

feat: add page querystring to url at solution

---

apps/web/src/app/[locale]/aot-2023/_components/tiltable-card.tsx

For context: see this tweet :
https://twitter.com/HugeLeters/status/1738596106034946139
Closes #1344
It's an accessibility issue.
I tested it on local dev, i took care to prevent default so that the page don't fully reloads, but uses the router.

Show Avent Of Code cards as links once they are flipped

---

apps/web/src/app/[locale]/_components/hero.tsx
apps/web/src/components/Navigation/index.tsx

This PR removes the `z-index` from the header, which is the cause of elements in the header clipping
through tooltips that show over it.
N/A
This was an issue on the challenge page, as the tooltips of the buttons that are at the top of the
code editor show up over the header.
I've confirmed that all the links and buttons in the header appears to work correctly without a
`z-index`, so it should be fine.
Before the change:
After the change:

fix: remove `z-index` from header

---

apps/web/src/app/[locale]/challenge/[slug]/left-wrapper.tsx

Removes z-index
removed the unneccesary z-index in challenges tabs in left-wrapper
Closes #

fix: challenges tabs z-index fix

---

apps/web/src/app/not-found.tsx

This PR fixes the header not being clickable on the 404 page.
N/A
The fix is identical to what I did for the overlap on the landing page.
I tested this locally and can confirm that it works fine on both mobile and desktop.
https://github.com/typehero/typehero/assets/38114607/97b13a95-694a-44b0-b357-83b139f149fd

fix: fix header overlap on 404 page

---

apps/web/src/app/[locale]/challenge/[slug]/submissions/[[...catchAll]]/_components/overview.tsx
packages/ui/src/components/markdown.tsx

adds copy button for code markdown snippets 
Closes #

feat: copy button for markdown

---

challenges/literal-types/prompt.md

This pull request addresses the issue related to the extra space in the description of literal types
[Remove extra space literal types](https://github.com/typehero/typehero/issues/1373)
Remove the extra space

Remove extra space literal types prompt.md

---

packages/db/mocks/challenges.mock.ts

It turns out that the tsconfig for each type challenge is included in the `info.yml` file, so manual
overrides aren't necessary (facepalm).
N/A
Given that the TypeScript playground URLs that the Type Challenges website redirects have to be
generated somehow, I should've realized that the tsconfig must be defined _somewhere_, but oh well
:D
I've confirmed locally that the prod seed script still works and correctly picks up the tsconfig of
the only challenge that has one (Assert Array Index).
N/A

chore: use tsconfig from info

---

apps/web/src/utils/server/get-similar-challenges.ts

when no session i am returning challengesByDifficulty and not including solved solution parameters in which session is required.
Also in notIn parameter passing the current challengeId so that same challenges should not be recommened again.
https://github.com/typehero/typehero/issues/1383
Closes #

fix: no session return more-challenges only by difficulty

---

challenges/validate.ts

This PR is in regards to this [bug](https://github.com/typehero/typehero/issues/1174). At the moment the command is failing because it doesn't know how to handle `aot`, which has no metadata.json file.
Issue: https://github.com/typehero/typehero/issues/1174
On top, `aot` introduces a new pattern to the `challenges` folder, that didn't exist when `validate.ts` was written. If we are going to create seasonal challenges, and then add them to the `/challenges` directory as new directories, then the `validate.ts` code will probably need to be updated to handle this additional directory layer. 
This PR puts a band aide on the issue and allows users to run this `pnpm` command, although additional work will probably need to be done to address new aots, or any other seasonal challenges. …

Filter out 'aot' challenge from getChallengeIds()

---

challenges/primitive-data-types/prompt.md

Grammer and typo fix in challenges/primitive-data-types/prompt.md
original->
", so too does TypeScript then not define types like `short` and `long`"
changed to ->
",similarly, TypeScript does not define types like `short` and `long`"
Enhancing clarity and readability

Grammer and typo fix

---

apps/web/src/app/[locale]/challenge/[slug]/left-wrapper.tsx

When not enrolled from any track, two problem explorer were popping up,
Removed the old boolean statement which used to check whether explorer is disabled or not,
and showed the ui for problem explorer, now it just checks whether the currect problem is a track challenge or not which is null if user is not enrolled in any track automatically
Closes #

fix: double problem explorer issue

---

LOCAL.md

With PlanetScale removing their hobby tier, we shouldn't be pushing people over to their service for a local-only project that they will likely have to pay for.
Updates the LOCAL.md file to remove the recommendation for PlanetScale in local dev. Now we only have instructions for Docker, with a mention for any MySQL compatible host that works with Prisma.
N/A
Planetscale removed their hobby tier and we were pushing people to planetscale
N/A
It's an MD file.

docs: Remove PlanetScale recommendation for local setup

---

apps/web/src/app/[locale]/explore/_components/explore-slug.tsx

On the explore page for a challenge (see [hard](https://typehero.dev/explore/hard)), I would like the challenges that have not been solved to be shown first.
I added a sort to the list of challenges returned from the query that pushes the completed challenges to the bottom
Closes #1427
Fixes #1427

feat: show challenges that have not been completed first

---

challenges/aot/2023/10/user.ts

Basic starting type typo fix on challenge 10.
https://github.com/typehero/typehero/issues/1431
Closes #1431

fix: challenge ten type typo

---

apps/web/src/utils/useLocalStorage.ts

Checking if `window` object exists using `typeof` to prevent reference error on server.
Closes #1467 
Avoid reference error for `window` object when a page using `useLocalStorage` hook is partially rendered on server.
Fixes #1467 
Visited home page.

Fix: check 'window' object using typeof in useLocalStorage hook

---

apps/aot/package.json
packages/auth/package.json
packages/db/package.json
packages/db/schema.prisma
pnpm-lock.yaml

admin site is broken with the following logs
```
[31m[auth][cause][0m: PrismaClientInitializationError: 
Invalid `prisma.session.findUnique()` invocation:
Prisma Client could not locate the Query Engine for runtime "rhel-openssl-1.0.x".
This happened because Prisma Client was generated for "rhel-openssl-3.0.x", but the actual deployment required "rhel-openssl-1.0.x".
Add "rhel-openssl-1.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:
generator client {
provider      = "prisma-client-js"
binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
The following locations have been searched:
/var/task/node_modules/.prisma/client
/var/task/node_modules/@prisma/client
/vercel/path0/node_modules/@prisma/client
/tmp/prisma-engines
/var/task/packages/db
at …
```

chore: align prisma + add targets

---

apps/web/src/app/challenge/_components/comments/comments.hooks.tsx
apps/web/src/app/challenge/_components/comments/getCommentRouteData.ts
apps/web/src/components/Navigation/index.tsx

Added checks to prevent a value of 0 from being passed as the page parameter for the paginated solution comments API.
Fixes #1504
When deleting the last comment on a solution, the client was fetching paginated comments with a page parameter value of 0. I have added checks on the client to prevent invalid values from being passed to the API call. Additionally, I have added a check on the server to prevent negative values from being passed as the `skip` parameter for Prisma.
Tested by deleting the last comment on a solution, ensuring that the request made to the server contains a page parameter value of 1.
Last Comment:
Proper page parameter passed:

fix: Prevent '0' being passed as the page param to paginated solution comments api

---

apps/web/src/components/Navigation/index.tsx
packages/db/schema.prisma
turbo.json

Does this make sense?
leverage `type` for notification templating (eg: `liked your comment`, `replied to your comment/solution`, `{x} mentioned you`
currently we'll only do notifications comment activity (like/reply) and submitted solutions(like/reply)

add: schema for notifications

---

package.json

should fix:
```
Run npx tsx tooling/scripts/contributors.ts
node:internal/process/esm_loader:40
internalBinding('errors').triggerUncaughtException(
^
Error: tsx must be loaded with --import instead of --loader
The --loader flag was deprecated in Node v20.6.0
at X (file:///home/runner/work/typehero/typehero/node_modules/tsx/dist/esm/index.mjs:1:1920)
at Hooks.addCustomLoader (node:internal/modules/esm/hooks:202:24)
at Hooks.register (node:internal/modules/esm/hooks:16[8](https://github.com/typehero/typehero/actions/runs/10623717194/job/29450679042#step:4:9):16)
at async initializeHooks (node:internal/modules/esm/utils:233:5)
at async customizedModuleWorker (node:internal/modules/esm/worker:[10](https://github.com/typehero/typehero/actions/runs/10623717194/job/29450679042#step:4:11)4:24) …
```

Fix root to be ESM 😵

---

apps/web/src/app/challenge/_components/comments/enhanced-user-badge.tsx

Added light mode variants for the gradients of titles.

fix: Light mode variant of colors for the title gradients

---

packages/monaco/src/code-editor.tsx

Looked through the source code of the [loader](https://github.com/suren-atoyan/monaco-loader?tab=readme-ov-file#init) and compared it to some other playgrounds. It appears you can just link the `loader.js` from the CDN directly.
Prior, we were running a script that would download all of monaco and TS and place them in our `public` folder. It appears that was unnecessary. 
Hoping I can dynamically change the TS version in the playground and reload the playground accordingly

change: load monaco from cdn

---

packages/db/.eslintrc.cjs
packages/db/mocks/challenges.mock.ts
packages/db/mocks/test-overrides/31824.ts
packages/db/tsconfig.json

This PR allows overriding test cases of type challenges during ingestion.
In particular, this PR overrides the test cases for [Length of String 3](https://github.com/type-challenges/type-challenges/tree/main/questions/31824-hard-length-of-string-3),
as the official tests cause TypeScript to fail, due to the `Gened` type producing "too large
unions".
N/A
It allows the "Length of String 3" challenge to be solved on TypeHero.
I tested the seed script locally and confirmed that the overridden tests get ingested.
N/A

fix: override test cases for "Length of String 3"

---

apps/web/src/app/challenge/_components/comments/comment-input.tsx
apps/web/src/app/challenge/_components/comments/comment.tsx

As of now, you could only reply to parent comment. 
This PR adds the functionality to be able to add sibling comments to other replies. Additionally, when you reply to another reply comment, the "username" tag of the user you are replying to gets autofilled in the input for better UX.
Closes #1605 
The website was a bit restrictive and inconsistent where you could only reply to original comments -- this functionality was disabled in case of reply comments.  The PR adds functionality of adding comments to replies as "sibling comments" and also referencing the "recipient" of the reply for better UX.
I've exposed two things -- textarea element and a function to set the input value out of `CommentInput` component to control it from the parent component -- `Comment`.
- We use `setInputValue` …

Adds functionality to reply to replies

---

apps/aot/src/app/events/[year]/page.tsx
apps/aot/src/server/api/routers/event.ts

fixed the query so that we can get the day, previously using the id would not equal to the actual day of advent.
We can also use select in the query and it will only get what is necessary for us.
before:
```
{
aot:dev:     id: <redacted>,
aot:dev:     createdAt: 2024-10-26T20:23:40.985Z,
aot:dev:     updatedAt: 2024-11-20T01:10:41.166Z,
aot:dev:     difficulty: 'EVENT',
aot:dev:     name: '2024 Day Nine',
aot:dev:     slug: '2024-9',
aot:dev:     description: <redacted>,
aot:dev:     shortDescription: '2024 Day Nine of Advent of Typescript',
aot:dev:     code: <redacted>,
aot:dev:     tests: <redacted>,
aot:dev:     status: 'ACTIVE',
aot:dev:     tsconfig: { strict: true },
aot:dev:     userId: <redacted>,
aot:dev:     user: { name: 'TypeHero' },
aot:dev:     hasSolved: false,
aot:dev: …
```

fix day numbers and also make query to get challenges much more succinct

---

apps/aot/src/app/events/(leaderboard)/_components/leaderboard-page.tsx

Make leaderboard links clickable
Adds `pointer-events: none` to the ring animation element so that the leaderboard that's behind it is clickable. Could probably also be fixed w/ `z-index` or `position: relative` on the leaderboard element.
Lmk if i should change what i've done!
Closes #1688
The user names seem like they should be clickable (they're links!), but you can't.
Tested by manually editing the styles in the dev tools. I couldn't install packages due to some patches not being applied :confused:.
Video from issue showing it working after adding `pointer-events: none`:
https://github.com/user-attachments/assets/6184c72b-91f6-4bcc-a9b0-9b2602216f83

fix: make leaderboard links clickable

---

packages/monaco/src/split-editor.tsx

the inlayHints Provider needs to be disposed with Split editor unmounts otherwise hints linger...
https://bsky.app/profile/tylur.dev/post/3lc75ea7zf22d
it was broken
ran it locally
**Before**
**After**

fix: inlay not updating when switching event to event

---

challenges/aot/2023/21/user.ts

Yeah, I'm a bit slow and still working on last year's challenges... Anyway, there's a small typo in 2023 Day 21 and this PR fixes it.
Closes #1702 
To remove a typo.
This is directly in the challenge contents, not related to the website. I'm not aware of further tests required. Let me know if I missed anything.

fix: Typo in 2023 Day 21

---

apps/aot/src/utils/default-avatar.tsx
apps/web/src/app/(profile)/[username]/completed/_components/challenges.tsx
packages/ui/src/components/avatar.tsx
packages/ui/src/components/default-avatar.tsx

The width of explore cards is overflowing on the "completed" page of your profile.
This PR fixes the issue.
I've tested this locally on various device viewports -- seems okay!
the issue:
after the fix:
cc: @bautistaaa

fixes explore cards width overflow

---

apps/web/src/app/(profile)/[username]/completed/page.tsx

Currently, we can see event challenges which users have solved in the *completed* section. This is not intended. 
This PR modifies the page query to not include these type of challenges on the page.
`+` This PR also fixes a minor navigation issue on production.
Closes #1706 
I've tested this by locally modifying challenge type as "EVENT" and ensuring if the db query filters out the challenge from completed section.
N/A
cc: @bautistaaa

do not query event challenges in completed section

---

apps/web/src/app/explore/_components/explore-section.tsx

I fixed the issue where the title background color of the Learners section appeared pink instead of green on the `/explore` page route.
Please see the screenshot below.
Closes #1721 
After testing on all browsers, the green background works as expected.

style: Remove pink blur and apply green for Learners section in explore page
