- .gitignore
- README.md
- logo.svg
> update: add logo properly to the README

- CONTRIBUTING.md
Minor corrections to the contributing guide
> docs: correct some of the steps in the contributing guide

- packages/monaco/src/index.tsx
- packages/monaco/src/split-editor.tsx
closes https://github.com/bautistaaa/typehero/issues/400
> (fix) local storage bug in code editor

- packages/monaco/monaco-vim.d.ts
- packages/monaco/src/index.tsx
- packages/monaco/src/vim-mode.tsx
- packages/monaco/tsconfig.json
we can now use `K` to launch the editor hover
> added `K` keymap to vim

- apps/admin/package.json
- apps/admin/src/app/_components/TabView.tsx
- apps/admin/src/app/_components/admin.actions.tsx
- apps/admin/src/app/_components/tracks/columns.tsx
- apps/admin/src/app/_components/users.tsx
- apps/admin/src/app/challenge/[challengeId]/challenge-review.tsx
- apps/admin/src/app/page.tsx
- apps/admin/src/app/tracks/[trackId]/_components/update-track-form.tsx
- apps/web/package.json
drive tab selection via query params
> quality of life to admin panel

- apps/web/src/app/explore/_components/explore-card-skeleton.tsx
- apps/web/src/app/explore/_components/explore-card.tsx
- apps/web/src/app/explore/_components/explore-slug-skeleton.tsx
- apps/web/src/app/explore/_components/explore-slug.tsx
- apps/web/src/app/explore/_components/index.tsx
- apps/web/src/app/explore/_components/section-carousel.tsx
- apps/web/src/app/explore/_components/section-skeleton.tsx
- apps/web/src/app/explore/_components/section.tsx
- apps/web/src/components/landing/community/community.tsx
- apps/web/src/components/landing/hero.tsx
- packages/ui/src/components/difficulty-badge.tsx
closes #395 
https://github.com/bautistaaa/typehero/assets/31113245/f69cce51-5509-4f0c-8253-1a0c99d02765
> Explore card redesign closes #395

- apps/web/src/app/challenge/_components/comments/comment-input.tsx
- apps/web/src/app/challenge/_components/comments/comment.tsx
- apps/web/src/app/challenge/_components/comments/index.tsx
- apps/web/src/components/ui/markdown.tsx
comments
https://github.com/bautistaaa/typehero/assets/31113245/430703eb-9d8c-402f-9087-28b93da3696d
comment editing
> comments design tweak

- apps/web/src/components/user/dashboard/index.tsx
- apps/web/src/components/user/dashboard/user-header.tsx
This PR removes the `ReportDialog` component from a user's profile when they visit their own profile 👍🏻
> Remove ReportDialog component for own profile

- apps/web/global.d.ts
- apps/web/package.json
- apps/web/src/app/api/auth/creds/route.ts
- apps/web/src/app/api/flags/route.ts
- apps/web/src/app/page.tsx
- apps/web/src/app/providers.tsx
- apps/web/src/components/ui/navigation.tsx
- apps/web/src/middleware.ts
- apps/web/src/utils/feature-flags.ts
- apps/web/src/utils/featureFlags.ts
- pnpm-lock.yaml
- turbo.json
this add feature flags and only allows you to to `/` and `/waitlist` hypothetically.
The edge DB has this for all envs set currently:
```
{
"exploreButton": false,
"loginButton": false
}
```
> Add feature flags

- .github/workflows/quality.yml
The main branch is `main` and not `master`
> ci: run on main

- packages/ui/src/components/alert.tsx
> Fixes an icon padding on https://www.typehero.dev/waitlist

- apps/web/src/app/feature-flag-provider.tsx
- apps/web/src/components/ui/navigation.tsx
- apps/web/src/middleware.ts
> use mock feature flags locally

- apps/web/src/utils/feature-flags.ts
- turbo.json
Should fix the eslint issue on main.
> fix: type issue in feature flags, missing env var in turbo.json

- LOCAL.md
- apps/web/next.config.js
- apps/web/next.config.mjs
- apps/web/package.json
- apps/web/src/app/providers.tsx
- package.json
- patches/@vercel__toolbar@0.1.1.patch
- pnpm-lock.yaml
thanks @anthonyshew this is really cool!
> Add vercel toolbar to localhost for comments

- apps/web/src/components/landing/waitlist/create.action.ts
- apps/web/src/components/landing/waitlist/waitlist-form.tsx
quick dirty way to show that we have their email already
> hotfix error message

- .github/ISSUE_TEMPLATE/bug.yml
- All option for bug report template
> add all option for bug report

- .gitignore
We should have a few of us that can push to DBs so we might have these files on our local fs.
> Add envs to gitignore

- apps/web/src/app/explore/_components/index.tsx
- apps/web/src/app/tracks/_components/index.tsx
- apps/web/src/app/tracks/_components/track-card.tsx
- apps/web/src/app/tracks/_components/track-challenge-card.tsx
- apps/web/src/app/tracks/_components/track-grid.tsx
- apps/web/src/components/ui/navigation.tsx
- packages/db/seed/index.ts
- cleans up seed script
- remove welcome to on the index pages 😜 
- adjust font on navigation
- handles ordering + limiting results in the query vs in component
- removes popular section since we are launching with only 4 - 5 tracks
> misc track + ui cleanup

- apps/web/src/app/challenge/_components/comments/index.tsx
> fix: Comment sorting should not show if theres no comments

- .ignore
- packages/monaco/tailwind.config.ts
- packages/ui/tailwind.config.ts
- adds tailwind autocomplete to packages/monaco and packages/ui
- removes the monaco deps from grep
> fixes tailwind autocomplete and grep ignores

- apps/web/src/app/waitlist/_components/waitlist-form.tsx
- packages/email/yarn.lock
Should remove the error from #548. 
Error might have been due to the fact that `{...field}` here passes down an extra ref that SelectPrimitive is not executing forwardRef on
Shadcn's documentation also doesn't pass down the rest of the `field` object when using Select component with react-hook-form inside a FormField
> 548 - Fixed waitlist form error

- apps/web/next.config.mjs
- apps/web/package.json
- apps/web/turbo.json
- packages/ui/src/components/markdown.tsx
- pnpm-lock.yaml
Main page before:
Main page after:
> perf(web): improve bundle size

- packages/ui/src/components/markdown.tsx
> wrap code in description

- README.md
- apps/web/src/app/_components/community/community.tsx
- apps/web/src/app/_components/hero.tsx
- tooling/scripts/contributors.ts
> Updates org from bautistaaa to typehero

- apps/admin/src/app/layout.tsx
- apps/web/src/app/[username]/page.tsx
- apps/web/src/app/_components/features.tsx
- apps/web/src/app/challenge/[id]/page.tsx
- apps/web/src/app/challenge/[id]/solutions/[solutionId]/page.tsx
- apps/web/src/app/challenge/[id]/solutions/page.tsx
- apps/web/src/app/challenge/[id]/submissions/page.tsx
- apps/web/src/app/explore/[slug]/page.tsx
- apps/web/src/app/explore/error.tsx
- apps/web/src/app/explore/page.tsx
- apps/web/src/app/layout.tsx
- apps/web/src/app/metadata.ts
- apps/web/src/app/page.tsx
- apps/web/src/app/settings/page.tsx
- apps/web/src/app/tracks/[slug]/page.tsx
- apps/web/src/app/tracks/page.tsx
- apps/web/src/app/waitlist/_components/create.action.ts
- apps/web/src/app/waitlist/page.tsx
- apps/web/src/app/wizard/page.tsx
- apps/web/src/components/ui/footsies.tsx
- apps/web/src/components/user/profile.tsx
- packages/email/emails/waitlist-user-signup.tsx
Added titles to (I think) all pages, and updated "Typehero" to "TypeHero".
Page titles are now similar to "Explore Challenges | TypeHero" and "Solutions to Hello World | TypeHero".
first OSS contribution, please give feedback
> Add titles + descriptions to pages

- apps/web/src/app/_components/feature-card.tsx
> fix challenge card step on light mode

- apps/web/src/app/explore/_components/explore-slug-skeleton.tsx
Before
https://github.com/typehero/typehero/assets/32938743/60b9c16b-10a2-46b9-8687-7a34c9c698b0
After
https://github.com/typehero/typehero/assets/32938743/6ed9722e-4b07-498e-97f8-84e49b1559a6
> Added new skeleton loader for explore slug

- .vscode/settings.json
- fixes an issue where prettier didn't work for vscode users
> fixes prettier for vscode

- apps/web/src/app/challenge/_components/comments/comment.tsx
I've updated the design of the comment. 
Before
https://github.com/typehero/typehero/assets/32938743/99b676ab-01d4-4b3c-9618-f1c067f5c8ec
After
https://github.com/typehero/typehero/assets/32938743/12afc38f-4c0e-4a81-aae8-68dd74e019cc
> Updated the deisgn of comments

- apps/web/src/app/challenge/_components/challenge-layout.tsx
~* Go under 500? Go to 0~
~* Go over 10? Go to 500+~
Now it works by:
Goes down to 500, stops, then at 300 its collapses to 0
At 300 it'll go back to 500 and back up as you keep moving over.
Also double click will collapse / open as well.
> newest new panel collapse

- apps/web/src/app/challenge/_components/comments/comment.tsx
Updated the comments.tsx file to include the toggle reply count button
https://github.com/typehero/typehero/assets/32938743/8ff99071-8939-4278-8d7f-8e3bffb5e692
@PickleNik
> Added inline reply count

- apps/web/src/app/[locale]/_components/community/community.tsx
- apps/web/src/app/[locale]/_components/feature-card.tsx
- apps/web/src/styles/globals.css
> fix million contributors grid & amogi not visible on mobile

- apps/web/next.config.mjs
web:dev: [vercel-toolbar] No project info found. Make sure you run `vc link` in your project directory.
web:dev: `source` does not start with / for route {"source":"min/vs/(.*)","headers":[{"key":"Access-Control-Allow-Origin","value":"*"},{"key":"Access-Control-Allow-Methods","value":"GET"}]}
web:dev:
web:dev:
web:dev: Error: Invalid header found
> fix error dev not booting up

- apps/web/src/app/[locale]/challenge/_components/description/index.tsx
- apps/web/src/app/[locale]/challenge/_components/editor-shortcuts/editor-shortcuts-button.tsx
- apps/web/src/app/[locale]/challenge/_components/settings/settings-button.tsx
- apps/web/src/app/[locale]/challenge/_components/share-form.tsx
- turbo.json
modals were hardcoded to 200 width
> fix: modals were not responsive

- apps/web/src/app/[locale]/privacy/page.tsx
- apps/web/src/app/[locale]/tos/page.tsx
- apps/web/src/components/ui/footsies.tsx
Add `/tos` && `/privacy` and add to footies, imo i didnt make good looking in most cases
cc @PickleNik
> Add Privacy Policy && ToS

- apps/web/src/app/[locale]/tracks/_components/track-challenge-card.tsx
> fix(track): tracks not visible on mobile devices

- apps/admin/src/components/navigation.tsx
- apps/og-image/app/components/logo.tsx
- apps/og-image/app/components/logo3d.tsx
- apps/web/.gitignore
- apps/web/src/app/[locale]/_components/hero.tsx
- apps/web/src/app/providers.tsx
- apps/web/src/components/navigation.tsx
- apps/web/src/components/toolbar.tsx
- move toolbar to its own component + wrap in suspense
- fix all the html errors regarding `clip-rule` & `fill-rule`
> chore: misc cleanup

- apps/web/src/components/footsies.tsx
> Footer adjustments

- apps/web/src/app/[locale]/settings/_components/appearance.tsx
- apps/web/src/app/[locale]/settings/_components/new-settings.tsx
- apps/web/src/app/[locale]/settings/_components/profile.tsx
I fixed updating the profile by putting the server actions back.
> Fix profile updating and disable some buttons

- apps/web/src/app/[locale]/challenge/_components/editor-shortcuts/editor-shortcuts-form.tsx
- apps/web/src/components/footsies.tsx
Remove irrelevant shortcuts (Run and Submit code)
Update inaccurate shortcuts
Dynamic shortcut rendering for mac OS (Alt and Ctrl key)
Closes #761 
Tested locally
> Fix : Editor shortcuts update #761

- apps/web/src/app/[locale]/settings/_components/new-settings.tsx
Added link on settings page
Closes #776
> feat:show links on settings page

- apps/web/src/app/layout.tsx
- apps/web/src/components/cookie-banner.tsx
Introduces a cookie consent banner 
Closes https://github.com/typehero/typehero/issues/777
https://github.com/typehero/typehero/assets/48399420/1f89ab3f-ff33-40b2-b513-4fa867a122cd
> feat: cookie consent banner

- packages/monaco/src/settings-store.ts
- packages/monaco/src/split-editor.tsx
- packages/monaco/src/vim-mode.tsx
> Add vim `gcc` command

- apps/web/src/app/[locale]/challenge/[id]/left-wrapper.tsx
Final version:
https://github.com/typehero/typehero/assets/53154523/90f9ab51-13ea-4d2f-833c-5aa6534effe4
> Added hover styles + spacing for the panel tabs in challenge layout

- apps/web/src/app/layout.tsx
- apps/web/src/components/navigation.tsx
- tooling/config-eslint/utils/rules.js
We are reverting this because it hurt perf pretty bad for people not close to the functions.
Closes #
> Revert server side nav

- apps/og-image/app/components/logo.tsx
- apps/og-image/app/components/logo3d.tsx
- apps/web/src/app/[locale]/_components/hero.tsx
- apps/web/src/components/navigation.tsx
We had warnings in the console because of invalid svg props being in the wrong case.
> fix: invalid svg props

- apps/web/src/app/layout.tsx
> Fix meta with this template thing 💀

- apps/web/src/app/layout.tsx
> Fix meta maybe

- apps/web/src/app/[locale]/(legal)/privacy/page.tsx
Fix typos and add necessary legal notes
> [!IMPORTANT]  
> **Before merging** make sure support@typehero.dev is a valid email address, I've linked it as a legal contact address in the privacy policy.
> Fix: Update Privacy Policy

- apps/web/src/app/[locale]/challenge/[id]/solutions/_components/solution-editor.tsx
- apps/web/src/app/[locale]/challenge/[id]/submissions/[[...catchAll]]/save-submission.action.ts
- apps/web/src/app/[locale]/challenge/[id]/wrapper.tsx
- apps/web/src/app/[locale]/challenge/increment.action.ts
- apps/web/src/app/[locale]/explore/_components/explore-section.tsx
- apps/web/src/app/[locale]/explore/_components/index.tsx
- apps/web/src/app/[locale]/tracks/[slug]/page.tsx
- apps/web/src/app/[locale]/tracks/_components/enroll-button.tsx
- apps/web/src/app/[locale]/tracks/_components/index.tsx
- apps/web/src/app/[locale]/tracks/_components/track-enrolled-section.tsx
- apps/web/src/app/[locale]/tracks/_components/track-grid.tsx
- apps/web/src/app/[locale]/tracks/_components/track.action.ts
- packages/monaco/src/index.tsx
- validate some mutations
- general cleanup
Closes #808
> chore: cleanup actions + cache

- apps/web/src/app/[locale]/claim/claim-form.tsx
- apps/web/src/app/[locale]/claim/page.tsx
- apps/web/src/app/[locale]/login/_components/LoginButton.tsx
- apps/web/src/app/[locale]/login/page.tsx
- apps/web/src/components/navigation.tsx
- apps/web/src/styles/globals.css
> fix theme buttn on mobile

- apps/web/src/app/[locale]/_components/community/community.tsx
- apps/web/src/app/[locale]/_components/feature-card.tsx
- apps/web/src/app/[locale]/_components/features.tsx
- apps/web/src/app/[locale]/tracks/_components/track-challenge-card.tsx
- packages/ui/src/components/badge.tsx
> Fix feature cards

- apps/web/src/app/[locale]/providers.tsx
- apps/web/src/styles/globals.css
https://github.com/typehero/typehero/assets/53154523/b8a0eb15-b415-4cbc-8121-0da57433d55b
Closes #794
> Changed tanstack devtools position to be less intrusive in dev env

- apps/web/src/app/[locale]/[username]/_components/dashboard/bookmarks-tab.tsx
- apps/web/src/app/[locale]/[username]/_components/dashboard/in-progress-tab.tsx
- apps/web/src/app/[locale]/[username]/_components/dashboard/index.tsx
- apps/web/src/app/[locale]/[username]/_components/dashboard/overview-tab.tsx
- apps/web/src/app/[locale]/[username]/_components/dashboard/shared-solutions-tab.tsx
- apps/web/src/app/[locale]/[username]/_components/profile.tsx
- apps/web/src/app/[locale]/[username]/bookmarks/page.tsx
- apps/web/src/app/[locale]/[username]/in-progress/page.tsx
- apps/web/src/app/[locale]/[username]/layout.tsx
- apps/web/src/app/[locale]/[username]/page.tsx
- apps/web/src/app/[locale]/[username]/shared-solutions/page.tsx
- apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/_actions.ts
- apps/web/src/app/[locale]/challenge/[slug]/submissions/[[...catchAll]]/save-submission.action.ts
- apps/web/src/app/[locale]/challenge/_components/bookmark.action.ts
- apps/web/src/app/[locale]/settings/_components/settings.tsx
- apps/web/src/utils/withUnstableCache.ts
Pay attention to the route changing when you click on each section!
https://github.com/typehero/typehero/assets/53154523/340137a7-cb08-4836-b88e-de7db9b082f0
Showing simple example of cache revalidation working for bookmarks and in-progress submissions:
https://github.com/typehero/typehero/assets/53154523/c04117a9-201c-42d2-9764-932e023e820a
Revalidation is also configured for the solutions as well!
> Make profile sections sub routes

- challenges/blank/tests.ts
- challenges/generic-type-arguments/tests.ts
- challenges/generic-type-constraints/tests.ts
- challenges/indexed-types/tests.ts
- challenges/literal-types/tests.ts
- challenges/primitive-data-types/tests.ts
- challenges/type-aliases/tests.ts
- challenges/type-unions/tests.ts
- challenges/typeof/tests.ts
- packages/db/seed/data/challenge-ingest.ts
- packages/monaco/src/editor-types.ts
importing is proving to be difficult. WIP PR: https://github.com/typehero/typehero/pull/890
in the mean time we can just full the test types locally and remove the imports from the test panel while this is still being worked on.
Closes #
> change test types and ingest script

- apps/admin/src/app/tracks/[trackId]/page.tsx
- apps/web/src/app/[locale]/tracks/[slug]/error.tsx
- apps/web/src/app/[locale]/tracks/_components/track-enrolled-section.tsx
- apps/web/src/app/[locale]/tracks/_components/track-grid.tsx
- apps/web/src/app/[locale]/tracks/_components/track.action.ts
- packages/db/mocks/challenges.mock.ts
- packages/db/schema.prisma
- packages/db/seed/prod.ts
- adds cache key for tracks
- tweaks prod seed
Closes #
> chore: seed + track fixes

- apps/web/src/app/[locale]/tracks/_components/track-grid.tsx
Reverting another key removal...
> revert key removal, again!

- apps/web/src/app/[locale]/tracks/_components/enroll-button.tsx
- apps/web/src/app/[locale]/tracks/_components/track.action.ts
> fix(tracks): prompt for user login before track enrollment

- apps/web/src/app/[locale]/challenge/_components/description/index.tsx
Radix Dialog uses button under the hood and thus it is causing the valid dom nesting warning , replaced the button with div
Closes #889
> chore: remove warning from console

- packages/ui/src/components/toast.tsx
Here is a video demo of all the states: 
1. dark:success
Hover:
2. dark:error
Hover:
3. light:success
Hover:
4. light:error
Hover:
https://github.com/typehero/typehero/assets/53154523/94976276-2b81-4ed2-940d-9c7cdab954fa
Closes #932
> Fixed colors for toast error/success

- apps/web/src/app/[locale]/layout.tsx
- apps/web/src/app/[locale]/page.tsx
- apps/web/src/app/[locale]/tracks/page.tsx
- apps/web/src/app/layout.tsx
- apps/web/src/app/metadata.ts
Closes https://github.com/typehero/typehero/issues/859
> fix: wrong page titles

- apps/web/src/app/[locale]/tracks/_components/track-card-soon.tsx
- apps/web/src/app/[locale]/tracks/_components/track-details.tsx
- apps/web/src/app/[locale]/tracks/_components/track-grid.tsx
- packages/db/seed/data/tracks.ts
- packages/db/temp/populate-tokens.ts
- disable coming soon tracks and 404 so users cant visit them directly
- quick fix to scripts
- 
Closes #
> chore: last min cleanup

- challenges/challenge-guidelines.md
- challenges/generic-function-arguments/metadata.json
- challenges/generic-function-arguments/prompt.md
- challenges/generic-function-arguments/solutions/1.ts
- challenges/generic-function-arguments/tests.ts
- challenges/generic-function-arguments/tsconfig.json
- challenges/generic-function-arguments/user.ts
- challenges/generic-type-arguments/prompt.md
- challenges/generic-type-constraints/prompt.md
- challenges/index-signatures/prompt.md
- challenges/indexed-types/prompt.md
- challenges/literal-types/prompt.md
- challenges/metadata.schema.json
- challenges/notes to dimitri.md
- challenges/type-aliases/prompt.md
- challenges/type-unions/prompt.md
- challenges/typeof/prompt.md
- added a new challenge for generic-function-arguments
- added a draft of a document on guidelines for creating challenges
> new(challenge): generic function arguments

- README.md
> Update language of sponsors section README.md

- docs/procedures/000-run-e2e-tests.md
Support was added for developers to write documentation for important processes that should be shared.
[GitHub Issue](https://github.com/typehero/typehero/issues/763)
This will help, when new contributors join, to describe processes in a way that will prevent the developer from coming and asking for help from other contributors. Reduce the need for contributors to repeat things to other contributors.
Also provides a single source of truth for how these processes should be carried out.
No tests are currently required for this task.
plicable):
This PR does not possess many documents itself. If you could send suggestions on the processes you think would be important, I am interested in writing them. Otherwise, there is an example document that other developers, with more domain knowledge, …
> Support for Documentation Added

- packages/auth/src/server.ts
> Update csrf cookie

- apps/web/src/app/[locale]/not-found.tsx
- apps/web/src/styles/globals.css
> fix mobile

- apps/web/src/app/[locale]/(email)/waitlist/_components/waitlist-form.tsx
> fix(waitlist): add detailed error messages for Mailchimp API

- challenges/literal-types/prompt.md
> Remove duplicated word

- challenges/index-signatures/tests.ts
closes https://github.com/typehero/typehero/pull/991
closes #989
This is a different attempt at the problem that (hopefully more naturally) attempts to make things clearer.
> [Feature] challenge(`index-signatures`): disallows `any` and `unknown`

- apps/web/src/app/[locale]/login/page.tsx
- apps/web/src/components/navigation.tsx
Added redirect param to redirect users to previous page
Closes #1036 
#1036
> 1036 redirect to original page after login

- apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/_actions.ts
- apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/solution-detail.tsx
Fixed the code for deleting the solution that trusted the id provided by the client.
related to #1044 same vulnerability, 
Closes #
> bug: removed dependency for solution.id from client

- apps/web/src/app/[locale]/_components/hero.tsx
- packages/ui/src/components/toast.tsx
Adding a general fix to all light mode issues I could find
Fixed these two:
1. Button color on hero section
2. Text color on default toast 
Closes #
Now
Before
> fix: light mode issues

- apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/delete/index.tsx
- apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/index.tsx
- apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/solution-detail.tsx
- apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/solution-editor.tsx
- apps/web/src/app/[locale]/challenge/[slug]/solutions/getSolutionRouteData.ts
- apps/web/src/app/[locale]/challenge/[slug]/solutions/page.tsx
Fixed:
1. Cache invalidation / query re-fetching on Solution Add / Delete
2. Removed redundant queries doing the same thing 
Closes #
1. Add a solution
Check for updates in solution row
2. Delete a solution
Check for updates in solution row
>  chore: fixed cache on solutions related routes and removed redundant queries

- apps/web/src/app/[locale]/explore/_components/explore-card.tsx
> fix: explore card description line height

- apps/web/src/app/[locale]/(profile)/[username]/_components/dashboard/_actions.ts
- apps/web/src/app/[locale]/(profile)/[username]/_components/dashboard/challenges-progress.tsx
- apps/web/src/app/[locale]/(profile)/[username]/_components/dashboard/overview-tab.tsx
- packages/ui/src/components/difficulty-badge.tsx
- packages/ui/src/components/progress.tsx
Added a UI to view number of challenges solved. 
Added
1. Total Challenges solved
2. Total Challenges
Closes #1083 
Tried to take motivation from multiple places, didn't find something useful. Made with suggestions from the community.
> feat: show number of problems solved on profile

- apps/web/src/app/[locale]/challenge/[slug]/solutions/_components/solution-detail.tsx
> added prose to solutions markdown 🌱

- packages/db/seed/data/challenge-ingest.ts
- packages/ui/src/components/markdown.tsx
- packages/ui/src/themes/vs-dark-plus.ts
- packages/ui/src/themes/vs.ts
> fix: type annotations in markdown

- challenges/mapped-object-types/prompt.md
Fix H --> h typo from issue #1107
Closes #1107
> lint fix case typo H --> h

- challenges/typeof/prompt.md
Just continuing to PR minor typos as I do challenges :)
> fix minor typo in typeof prompt

- apps/web/src/app/[locale]/tracks/_components/track-card.tsx
- apps/web/src/app/[locale]/tracks/_components/track-details.tsx
- apps/web/src/app/[locale]/tracks/_components/track-grid.tsx
- apps/web/src/app/[locale]/tracks/_components/track-progress.tsx
- apps/web/src/app/[locale]/tracks/_components/track.action.ts
- packages/ui/src/components/badge.tsx
Making the UI reflect when a user has finished all the track tasks.
Closes # [Issue](https://github.com/typehero/typehero/issues/1178)
> feat: indicate when a track is finished

- apps/web/src/app/[locale]/aot-2023/_components/about.tsx
- apps/web/src/app/[locale]/aot-2023/_components/index.tsx
> fix: aot landing on mobile

- apps/web/src/app/[locale]/aot-2023/_components/about.tsx
lmk any copy feedback or thoughts on the colors
Click "About" on the AoT landing.
|Mobile|Desktop|
|---|---|
|<img width="387" alt="Screenshot 2023-11-29 at 2 53 31 PM" src="https://github.com/typehero/typehero/assets/7817695/edd233fc-1e46-43c2-b491-3a9776c50a59">|<img width="1182" alt="Screenshot 2023-11-29 at 2 55 40 PM" src="https://github.com/typehero/typehero/assets/7817695/ecd20de1-e524-4289-85f0-f0be7ae7c68e">|
Then, see the `Rewards` section in the `About` pane.
|Mobile|Desktop|
|---|---|
|<img width="388" alt="image" src="https://github.com/typehero/typehero/assets/7817695/f551e7e7-4d2a-4332-8b8c-e4a6b659a506"><img width="387" alt="image" src="https://github.com/typehero/typehero/assets/7817695/dc758af9-ee39-4f41-a79d-d1a7617a9237"><img width="389" alt="image" …
> feat: add rewards+badges section under "About" aot

- apps/web/src/app/[locale]/_components/countdown-timer.tsx
- apps/web/src/app/[locale]/aot-2023/_components/index.tsx
Reference #1235 
Added dynamic date update subheader above countdown
> Add dynamic countdown logic

- apps/web/src/app/[locale]/challenge/_components/description/index.tsx
- apps/web/src/app/[locale]/challenge/_components/description/suggestions-skeleton.tsx
- apps/web/src/app/[locale]/challenge/_components/description/suggestions.tsx
- apps/web/src/app/[locale]/tracks/_components/track-challenge-card.tsx
Added suggestions on the challenges description page.
It shows 3 similar challenges for the current challenge on the description page.
Closes 
Dark:
Light:
Skeleton Dark:
Skeleton Light:
> feat: add challenge suggestions with problem.

- apps/web/src/app/[locale]/challenge/_components/description/index.tsx
> bug: aot challenges visible on recommendation

- apps/web/src/components/Navigation/index.tsx
- apps/web/src/components/Navigation/theme-button.tsx
- apps/web/src/components/footsies.tsx
Before:
Light:
Dark:
After:
Light:
Dark:
> chore: Reposition theme button

- apps/web/src/components/search/search.tsx
Desktop:
Mobile:
Hover:
Desktop:
Mobile:
Hover:
Closes #1284
> Search bar responsive + style changes

- packages/ui/src/components/toast.tsx
- packages/ui/src/components/toaster.tsx
Fixes the dismiss button in the toast component
Closes # https://github.com/typehero/typehero/issues/1298
https://github.com/typehero/typehero/assets/131662061/d4b23658-4199-4ead-b6b8-d6ac4b26b99a
> fix: toast dismissal

- packages/auth/package.json
- packages/auth/src/server.ts
- pnpm-lock.yaml
Removed the `@next-auth/prisma-adapter` and  after installed `@auth/prisma-adapter` as described in the issue's description. Changed the `PrismaAdapter` import from `@next-auth/prisma-adapter` to `@auth/prisma-adapter` in `packages/auth/src/server.ts`
Closes https://github.com/typehero/typehero/issues/1281
> prisma-adapter updated (#1281)

- challenges/primitive-data-types/prompt.md
> fix minor typo

- apps/web/src/app/sitemap.ts
good seo, yes yes yes
This will add all the challanges to the sitemap.xml
note: I am not doing caching so if it could be abused methinks
> Make the sitemap.xml use the database for good SEO

- apps/web/src/app/[locale]/challenge/[slug]/getChallengeRouteData.ts
- apps/web/src/app/[locale]/challenge/[slug]/left-wrapper.tsx
- apps/web/src/app/[locale]/challenge/[slug]/page.tsx
- apps/web/src/app/[locale]/challenge/[slug]/submissions/[[...catchAll]]/save-submission.action.ts
This PR removes checks on the challenge view to enable comments and solution sharing
It also removes time checks for AOT specific challenges.
Closes #
> chore: remove aot checks

- apps/web/package.json
- apps/web/src/app/api/uploadthing/core.ts
- apps/web/src/app/api/uploadthing/route.ts
- apps/web/src/components/rich-markdown-editor.tsx
- apps/web/src/utils/domUtils.ts
- pnpm-lock.yaml
- Updates uploadthing to the latest stable version
- Removes the deprecated reliance on `document.execCommand`
Closes #
> Fix uploadthing

- challenges/default-generic-arguments/prompt.md
> Fix: repeated text in default generic arguments

- package.json
- pnpm-lock.yaml
because @anthonyshew said so
https://turbo.build/blog/turbo-1-13-0#new-terminal-ui
> chore: update to latest turbo

- package.json
- tooling/github-actions/install/action.yml
Related but seems like it is working now?
vercel/turbo#7993
> Update pnpm to latest v8

- package.json
- pnpm-lock.yaml
- tooling/github-actions/install/action.yml
> chore: upgrade pnpm

- apps/aot/src/app/globals.css
- apps/aot/src/app/layout.tsx
- apps/aot/src/app/page.tsx
https://github.com/user-attachments/assets/43cd97bf-a09d-4188-bc66-02709051336c
> (aot) coming soon page

- apps/web/src/app/challenge/[slug]/all-challenges.hook.tsx
- apps/web/src/app/challenge/[slug]/challenge-route-data.hook.tsx
- apps/web/src/app/challenge/[slug]/context-providers.tsx
- apps/web/src/app/challenge/[slug]/layout.tsx
- apps/web/src/app/challenge/_components/challenge-layout-wrapper.tsx
- apps/web/src/app/challenge/_components/sheet-content-custom.tsx
- apps/web/src/app/layout.tsx
- apps/web/src/components/Navigation/problem-explorer-nav.tsx
- apps/web/src/components/Navigation/problem-explorer-track-nav.tsx
This doesnt need to wrap the whole app, just the challenge route
Further refactors needed but nbd right now
> chore: move context closer to challenges

- challenges/primitive-data-types/prompt.md
In the challenge description for [Primitive Data Types](https://typehero.dev/challenge/primitive-data-types), there is no second point about "What Does Primitive mean in this context?"
Closes #1499
> Fix the typo in the challenge description of primitive-data-types

- apps/web/src/app/api/cron/sync-contributors/route.ts
> fix: contributor cron

- .github/workflows/contributors.yml
- tooling/scripts/.eslintrc.cjs
- tooling/scripts/contributors.ts
- tooling/scripts/turbo.json
- turbo.json
> Rname token

- package.json
This reverts commit 22387745ab1531265044df99d444eeb9a2061b46.
> Revert "Fix root to be ESM 😵 (#1525)"

- apps/web/src/components/Navigation/index.tsx
Closes #https://github.com/typehero/typehero/issues/1520
> feat: adds avatar instead of default user button

- apps/web/src/app/challenge/_components/comments/enhanced-user-badge.tsx
- apps/web/src/components/mention/user-results.tsx
> chore: fix light more mentions

- apps/web/src/app/providers.tsx
> fix: system theme issue

- apps/web/src/components/mention/mention-input.tsx
Closes #https://github.com/typehero/typehero/issues/1536
> fix: add space after adding a mention

- packages/monaco/src/code-editor.tsx
- packages/ui/src/components/markdown.tsx
Closes #1541 
https://github.com/user-attachments/assets/92c5030a-c303-4c9b-8e0d-783619519350
> fix:1541 system theme not working correctly

- apps/web/src/app/challenge/[slug]/getChallengeRouteData.ts
- apps/web/src/app/challenge/_components/description/index.tsx
> fix: switch name -> id

- apps/web/src/app/challenge/[slug]/submissions/[[...catchAll]]/_components/overview.tsx
- apps/web/src/components/share-url.tsx
Add short url copy dialog to Share button on submission.
Related to #1507
> feat: add short URL share dialog to share submission button

- packages/db/.eslintrc.cjs
- packages/db/temp/create-notifications.ts
add quick script to scaffold notifications
> chore: add noti script

- apps/web/src/app/challenge/[slug]/solutions/_components/solution-detail.tsx
Closes #1552 
https://github.com/user-attachments/assets/0c308463-a594-4380-9916-b52de360d02d
> fix:#1552  Pinning-solution-requires-refresh

- apps/web/src/app/challenge/[slug]/right-wrapper.tsx
- apps/web/src/app/challenge/_components/challenge-layout-wrapper.tsx
just a better name but not really
> chore: rename file

- apps/admin/package.json
- apps/aot/package.json
- apps/og-image/package.json
- apps/web/package.json
fix NextJS to use turbopack in the dev environment
> fix: next turbo

- apps/web/src/app/challenge/_components/bookmark.action.ts
> fix: bookmark validation

- apps/aot/src/app/leaderboard/layout.tsx
- apps/aot/src/utils/time-utils.ts
> bug-fix: isValidAdventDay incorrect logic

- apps/aot/src/app/events/[year]/page.tsx
- apps/aot/src/app/leaderboard/getAotChallengeIds.ts
- apps/aot/src/server/api/routers/event.ts
- apps/aot/src/utils/time-utils.ts
- Refactor how to get challengeId's: Now using trackChallenge mapping
- Added basic skeleton code for events page to get all challenges so far and render the rest of days with some sample jsx
> updating event page

- apps/aot/src/app/events/[year]/[day]/solutions/page.tsx
- apps/aot/src/app/events/[year]/page.tsx
- apps/aot/src/app/leaderboard/page.tsx
- apps/aot/src/app/login/page.tsx
- apps/aot/src/app/page.tsx
- apps/aot/src/utils/metadata.ts
- apps/og-image/app/api/aot-2024/route.tsx
- apps/og-image/app/page.tsx
> feat(aot): adds og image

- packages/monaco/src/split-editor.tsx
This PR refreshes inlay hints on every code change by the user.
After every code edit by the user,
- dispose the current hint provider and register a new one in its place (debounced by 1s)
- The new provider automatically fetches new hints according to the new code and renders them on the editor.
Closes #1621 
Again, this PR fixes #1621 which describes the issue of hints not updating after code changes. 
But wait a minute! This feature already works out of the box. Notice that when you change the Type on current production site and scroll on the "tests" editor -- the hints for the type will be updated as per the code change! You can test this on https://typehero.dev/challenge/day-6 by updating `type FilterChildrenBy = {};` and scrolling on "tests" editor)
- I noticed the fact …
> refresh inlay hints on code edits

- apps/aot/src/app/events/[year]/[day]/right-wrapper.tsx
- apps/web/src/app/challenge/[slug]/right-wrapper.tsx
> adding queryClient.invalidateQueries for challenge-solutions

- .github/workflows/contributors.yml
- .github/workflows/quality.yml
- tooling/github-actions/install/action.yml
> update gh actions to v4

- apps/aot/src/app/events/[year]/[day]/_components/comments/comment-input.tsx
- apps/aot/src/app/events/[year]/[day]/_components/comments/comment.tsx
copy pasta from web until i consolidate the madness
still need to test
> feat(comments): port comment enhancements from web

- apps/aot/src/app/events/[year]/[day]/_components/description/index.tsx
- apps/aot/src/app/events/[year]/[day]/layout.tsx
- apps/aot/src/app/events/[year]/[day]/page.tsx
- apps/aot/src/app/events/page.tsx
> fix: og image not showing on routes

- apps/aot/src/app/events/[year]/page.tsx
> fix jsx in events/[year]/page.tsx

- apps/aot/src/app/events/[year]/24BgDecorations.tsx
- apps/aot/src/app/events/[year]/GiftBox.tsx
- apps/aot/src/app/events/[year]/YearsSelector.tsx
- apps/aot/src/app/events/[year]/day-active.tsx
- apps/aot/src/app/events/[year]/day-inactive.tsx
- apps/aot/src/app/events/[year]/page.tsx
- apps/aot/src/app/globals.css
- apps/aot/src/components/landing/PartnerLink.tsx
- apps/aot/src/components/landing/Partners.tsx
- apps/aot/src/components/navigation/index.tsx
> finish transitions on events page, add partners and years selector

- apps/aot/src/app/events/[year]/[day]/submissions/[[...catchAll]]/_components/overview.tsx
- packages/ui/src/icons.ts
https://github.com/user-attachments/assets/e3e3b655-91f6-48a5-8cc4-e15ca89a136b
(ignore leaderboard, the data is not correct)
> add link to leaderboard on submission screen

- apps/aot/src/app/events/[year]/[day]/submissions/[[...catchAll]]/_components/overview.tsx
we dont need to share for aot (at least right now)
> chore: remove share code on success screen

- apps/aot/src/components/footsies.tsx
> chore(AoT): add discord in footer

- apps/aot/src/app/events/[year]/[day]/right-wrapper.tsx
- apps/aot/src/app/events/[year]/[day]/submissions/[[...catchAll]]/_components/overview.tsx
- apps/aot/src/app/events/[year]/[day]/submissions/[[...catchAll]]/getChallengeSubmissions.ts
Continuation from #1717, but for AOT.
cc @bautistaaa
> Enforce submission is only viewable by author for aot

- apps/aot/src/app/events/[year]/24BgDecorations.tsx
- apps/aot/src/app/events/[year]/Lights/Bulb.tsx
- apps/aot/src/app/events/[year]/Lights/Strip.tsx
- apps/aot/src/app/events/[year]/Lights/index.tsx
- apps/aot/src/app/events/[year]/page.tsx
- apps/aot/src/app/globals.css
https://github.com/user-attachments/assets/58ba9b24-dfb1-4d5c-b55f-c1aa7514d78b
> AoT Events Page lights decoration

- apps/web/src/components/Navigation/index.tsx
> fix: correct /edit route on mobile menu
